<?php

namespace FrontBundle\Repository;

/**
 * OperaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByParola($parola){
        return $this->getEntityManager()->createQuery(
                "SELECT o FROM FrontBundle:Opera o WHERE o.nome LIKE '%$parola%'" 
            )->getResult();
    }
}
